'use strict';
const fs=require('fs'),path=require('path'),dns=require('dns').promises,net=require('net'),http=require('http'),https=require('https'),crypto=require('crypto');
const express=require('express'),{WebSocketServer,WebSocket}=require('ws'),app=express();
const PORT=pos(process.env.PORT,2525),TIMEOUT=pos(process.env.UPSTREAM_TIMEOUT_MS,30000),MAX_BODY=pos(process.env.MAX_BODY_BYTES,16*1024*1024),WS_QUEUE_MAX=pos(process.env.WS_QUEUE_MAX_BYTES,1024*1024),SLOW_MS=pos(process.env.SLOW_REQUEST_MS,2000);
const UPSTREAM=new URL(process.env.UPSTREAM_ORIGIN||'https://bloxd.io');
const ROOTS=String(process.env.ALLOWED_ROOT_HOSTS||'bloxd.io,googleapis.com,gstatic.com,google.com,recaptcha.net,cloudflare.com,cloudflareinsights.com,unpkg.com,bytebrew.io,ytimg.com').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);
const LOG_DIR=path.resolve(process.env.LOG_DIR||path.join(__dirname,'logs'));fs.mkdirSync(LOG_DIR,{recursive:true});
const stamp=new Date().toISOString().replace(/[:.]/g,'-');const LOG_FILE=path.join(LOG_DIR,`proxy-${stamp}-${process.pid}-${crypto.randomBytes(3).toString('hex')}.log`);const LOG_STREAM=fs.createWriteStream(LOG_FILE,{flags:'a'});
function pos(v,f){const n=parseInt(v,10);return Number.isInteger(n)&&n>0?n:f;}
function clean(v){return String(v??'').replace(/([?&](?:token|key|code|auth|session|captcha|secret)=)[^&\s]+/gi,'$1[REDACTED]');}
function log(level,type,fields={}){const safe={};for(const[k,v]of Object.entries(fields))safe[k]=/cookie|authorization|token|body/i.test(k)?'[REDACTED]':clean(v);const line=JSON.stringify({time:new Date().toISOString(),level,type,...safe});LOG_STREAM.write(line+'\n');if(level==='error'||level==='warn'||type==='server-start'||type==='websocket-close')console[level==='error'?'error':level==='warn'?'warn':'log'](line);}
function allowed(h){h=h.toLowerCase().replace(/\.$/,'');return ROOTS.some(r=>h===r||h.endsWith('.'+r));}
function privateIp(ip){if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||p[0]>=224;}const x=ip.toLowerCase();return x==='::1'||x==='::'||x.startsWith('fc')||x.startsWith('fd')||/^fe[89ab]/.test(x);}
async function validate(u){if(!['http:','https:'].includes(u.protocol))throw Object.assign(new Error('Protocol denied'),{status:400});if(!allowed(u.hostname))throw Object.assign(new Error('Host denied'),{status:403});const a=await dns.lookup(u.hostname,{all:true,verbatim:true});if(!a.length||a.some(x=>privateIp(x.address)))throw Object.assign(new Error('Address denied'),{status:403});}
function decode64url(s){return Buffer.from(s.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8');}
function targetFor(req){if(req.path.startsWith('/__proxy/url/')){const u=new URL(decode64url(req.path.slice('/__proxy/url/'.length))+new URL(req.originalUrl,'http://x').search);if(['localhost','127.0.0.1','::1'].includes(u.hostname))return new URL(u.pathname+u.search,UPSTREAM);return u}return new URL(req.originalUrl,UPSTREAM);}
function localize(u){if(u.origin===UPSTREAM.origin)return u.pathname+u.search+u.hash;return '/__proxy/url/'+Buffer.from(u.href).toString('base64url');}
function strip(h){for(const n of ['connection','keep-alive','proxy-authenticate','proxy-authorization','te','trailer','transfer-encoding','upgrade','content-security-policy','content-security-policy-report-only','permissions-policy','content-length','content-encoding'])delete h[n];}
function injectHtml(buf){let s=buf.toString('utf8');const boot='<script src="/__proxy-local/proxy-runtime.js"></script><script>navigator.serviceWorker?.register("/__proxy-local/sw.js",{scope:"/"}).catch(console.warn)</script>';return Buffer.from(/<head[^>]*>/i.test(s)?s.replace(/<head([^>]*)>/i,`<head$1>${boot}`):boot+s);}
function rewriteCss(buf,target){return Buffer.from(buf.toString('utf8').replace(/url\((['"]?)([^'"\)]+)\1\)/gi,(m,q,x)=>{if(/^(?:data|blob):/i.test(x))return m;try{return `url(${q}${localize(new URL(x,target))}${q})`;}catch{return m;}}));}
function collect(s,limit=64*1024*1024){return new Promise((ok,no)=>{let n=0,a=[];s.on('data',c=>{n+=c.length;if(n>limit){no(new Error('Response too large'));s.destroy();}else a.push(c)});s.on('end',()=>ok(Buffer.concat(a)));s.on('error',no);});}
app.disable('x-powered-by');app.set('trust proxy',1);
app.get('/__proxy-local/sw.js',(q,r)=>{r.set('Service-Worker-Allowed','/');r.set('Cache-Control','no-store');r.type('js').sendFile(path.join(__dirname,'sw.js'));});
app.get('/__proxy-local/proxy-runtime.js',(q,r)=>{r.set('Cache-Control','no-store');r.type('js').sendFile(path.join(__dirname,'proxy-runtime.js'));});
app.get('/__proxy-local/healthz',(q,r)=>r.type('text').send('ok'));
const HTTP_AGENT=new http.Agent({keepAlive:true,maxSockets:128,maxFreeSockets:32,timeout:30000});const HTTPS_AGENT=new https.Agent({keepAlive:true,maxSockets:128,maxFreeSockets:32,timeout:30000});
app.use(async(req,res)=>{const started=Date.now();let target;try{target=targetFor(req);await validate(target);}catch(e){log('warn','request-denied',{message:e.message,url:req.originalUrl});return res.status(e.status||400).send(e.message);}
 const headers={};for(const[k,v]of Object.entries(req.headers))if(!['host','connection','proxy-connection','origin','referer','content-length','accept-encoding'].includes(k)&&v!=null)headers[k]=v;
 headers.host=target.host;headers.origin=UPSTREAM.origin;headers.referer=UPSTREAM.origin+'/';headers['accept-encoding']='identity';
 const tr=target.protocol==='https:'?https:http;const agent=target.protocol==='https:'?HTTPS_AGENT:HTTP_AGENT;
 const up=tr.request(target,{method:req.method,headers,timeout:TIMEOUT,agent},async remote=>{try{const rh={...remote.headers};const type=String(rh['content-type']||'').toLowerCase();if(rh.location){const u=new URL(rh.location,target);rh.location=localize(u);}const change=req.method==='GET'&&remote.statusCode===200&&(type.includes('text/html')||type.includes('text/css'));if(change){const b=await collect(remote),o=type.includes('text/html')?injectHtml(b):rewriteCss(b,target);strip(rh);rh['content-length']=String(o.length);rh['cache-control']='no-store';res.writeHead(remote.statusCode,rh);res.end(o);}else{for(const n of ['connection','keep-alive','proxy-authenticate','proxy-authorization','te','trailer','transfer-encoding','upgrade','content-security-policy','content-security-policy-report-only','permissions-policy'])delete rh[n];res.writeHead(remote.statusCode||502,rh);remote.pipe(res);}{const elapsedMs=Date.now()-started;if((remote.statusCode||0)>=400||elapsedMs>=SLOW_MS)log((remote.statusCode||0)>=500?'error':'warn','slow-or-error-upstream-response',{status:remote.statusCode,host:target.hostname,path:target.pathname,elapsedMs});}}catch(e){log('error','response-error',{message:e.message,host:target.hostname});if(!res.headersSent)res.status(502).send('Bad Gateway');else res.destroy(e);}});
 up.on('timeout',()=>up.destroy(new Error('Upstream timeout')));up.on('error',e=>{log('error','upstream-error',{message:e.message,host:target.hostname,path:target.pathname});if(!res.headersSent)res.status(502).send('Bad Gateway');else res.destroy(e);});let n=0;req.on('data',c=>{n+=c.length;if(n>MAX_BODY)up.destroy(new Error('Request body too large'));});req.pipe(up);
});
const server=app.listen(PORT,()=>log('info','server-start',{port:PORT,upstream:UPSTREAM.origin,logFile:LOG_FILE}));server.headersTimeout=TIMEOUT+5000;server.requestTimeout=TIMEOUT*2;server.keepAliveTimeout=15000;
const wss=new WebSocketServer({noServer:true,perMessageDeflate:false});const validCode=c=>Number.isInteger(c)&&((c>=1000&&c<=1014&&![1004,1005,1006].includes(c))||(c>=3000&&c<=4999));
server.on('upgrade',async(req,socket,head)=>{try{const ru=new URL(req.url,'http://x'),pre='/__proxy-ws/';if(!ru.pathname.startsWith(pre))return socket.destroy();const target=new URL(decode64url(ru.pathname.slice(pre.length))+ru.search);await validate(new URL(target.href.replace(/^ws:/,'http:').replace(/^wss:/,'https:')));wss.handleUpgrade(req,socket,head,client=>{const offered=String(req.headers['sec-websocket-protocol']||'').split(',').map(x=>x.trim()).filter(Boolean),queue=[];let qb=0,cm=0,cb=0,um=0,ub=0,openedAt=0;const h={Origin:UPSTREAM.origin,Referer:UPSTREAM.origin+'/',Host:target.host};if(req.headers['user-agent'])h['User-Agent']=req.headers['user-agent'];if(req.headers.cookie)h.Cookie=req.headers.cookie;const upstream=new WebSocket(target.href,offered.length?offered:undefined,{headers:h,handshakeTimeout:TIMEOUT,perMessageDeflate:false});client.on('message',(d,b)=>{cm++;cb+=d.length||0;if(upstream.readyState===WebSocket.OPEN)return upstream.send(d,{binary:b});if(qb+(d.length||0)>WS_QUEUE_MAX){log('warn','websocket-queue-overflow',{host:target.hostname,queuedBytes:qb});client.close(1013,'Queue limit');return upstream.terminate()}queue.push({d:Buffer.from(d),b});qb+=d.length||0});upstream.on('open',()=>{openedAt=Date.now();for(const m of queue)upstream.send(m.d,{binary:m.b});queue.length=0;qb=0});upstream.on('message',(d,b)=>{um++;ub+=d.length||0;if(client.readyState===WebSocket.OPEN)client.send(d,{binary:b})});client.on('close',(c,r)=>{try{if(upstream.readyState===WebSocket.OPEN){if(validCode(c))upstream.close(c,String(r).slice(0,123));else upstream.terminate()}else if(upstream.readyState===WebSocket.CONNECTING)upstream.terminate()}catch{}});upstream.on('close',(c,r)=>{log('info','websocket-close',{host:target.hostname,code:c,durationMs:openedAt?Date.now()-openedAt:0,clientMessages:cm,clientBytes:cb,upstreamMessages:um,upstreamBytes:ub,forwardedCode:validCode(c)?c:'terminate'});try{if(client.readyState===WebSocket.OPEN){if(validCode(c))client.close(c,String(r).slice(0,123));else client.terminate()}}catch{try{client.terminate()}catch{}}});upstream.on('error',e=>log('error','websocket-error',{host:target.hostname,message:e.message}));upstream.on('unexpected-response',(q,r)=>log('warn','websocket-unexpected-response',{host:target.hostname,status:r.statusCode||0}))})}catch(e){log('warn','websocket-denied',{message:e.message,url:req.url});socket.destroy()}});
for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>{LOG_STREAM.end(()=>process.exit(0))});
